//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.ApplicationData>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.ApplicationData>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.ApplicationData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.ApplicationData(this.GetEntityConnectionString(
                "_IntrinsicData",
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            return null;
        }
    
    #endregion
    
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class dbmanualsourceDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.dbmanualsourceData>
    {
    
        public dbmanualsourceDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).dbmanualsourceData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class dbmanualsourceDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.dbmanualsourceData>
    {
        public dbmanualsourceDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.cpn_final> mothers_cpnfinal(global::System.Nullable<long> idmother)
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.cpn_final> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.cpn_final>("cpn_finals"),
                (c) => (idmother.HasValue && (c.idmother == idmother)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.cpn> mother_cpns(global::System.Nullable<int> mother_id)
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.cpn> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.cpn>("cpns"),
                (c) => (mother_id.HasValue && (c.mother.id == mother_id)));
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.amostrastb))
            {
                return new global::LightSwitchApplication.Implementation.amostrastb();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ccr))
            {
                return new global::LightSwitchApplication.Implementation.ccr();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ccrseg))
            {
                return new global::LightSwitchApplication.Implementation.ccrseg();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.child))
            {
                return new global::LightSwitchApplication.Implementation.child();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.cpn_final))
            {
                return new global::LightSwitchApplication.Implementation.cpn_final();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.cpn))
            {
                return new global::LightSwitchApplication.Implementation.cpn();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.cpp))
            {
                return new global::LightSwitchApplication.Implementation.cpp();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.csr_pf))
            {
                return new global::LightSwitchApplication.Implementation.csr_pf();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.laboratoriotb))
            {
                return new global::LightSwitchApplication.Implementation.laboratoriotb();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.livro))
            {
                return new global::LightSwitchApplication.Implementation.livro();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.maternidade))
            {
                return new global::LightSwitchApplication.Implementation.maternidade();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.mother))
            {
                return new global::LightSwitchApplication.Implementation.mother();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.paciente_resistente_tb))
            {
                return new global::LightSwitchApplication.Implementation.paciente_resistente_tb();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.pacientetb))
            {
                return new global::LightSwitchApplication.Implementation.pacientetb();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.patient))
            {
                return new global::LightSwitchApplication.Implementation.patient();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_categoria))
            {
                return new global::LightSwitchApplication.Implementation.t_categoria();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_grauexposicao))
            {
                return new global::LightSwitchApplication.Implementation.t_grauexposicao();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_historia_clinica_notificacao))
            {
                return new global::LightSwitchApplication.Implementation.t_historia_clinica_notificacao();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_historiaclinica))
            {
                return new global::LightSwitchApplication.Implementation.t_historiaclinica();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_intervenco))
            {
                return new global::LightSwitchApplication.Implementation.t_intervenco();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_laboratorio_notificacao))
            {
                return new global::LightSwitchApplication.Implementation.t_laboratorio_notificacao();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_localacidente))
            {
                return new global::LightSwitchApplication.Implementation.t_localacidente();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_notificacao))
            {
                return new global::LightSwitchApplication.Implementation.t_notificacao();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_referencia))
            {
                return new global::LightSwitchApplication.Implementation.t_referencia();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_referido))
            {
                return new global::LightSwitchApplication.Implementation.t_referido();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_regimeppe))
            {
                return new global::LightSwitchApplication.Implementation.t_regimeppe();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_registodiarioppe))
            {
                return new global::LightSwitchApplication.Implementation.t_registodiarioppe();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_registodiariovgb))
            {
                return new global::LightSwitchApplication.Implementation.t_registodiariovgb();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_resultadosppe))
            {
                return new global::LightSwitchApplication.Implementation.t_resultadosppe();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_resultadoteste))
            {
                return new global::LightSwitchApplication.Implementation.t_resultadoteste();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_seguimento_notificacao))
            {
                return new global::LightSwitchApplication.Implementation.t_seguimento_notificacao();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_tipoviolencia))
            {
                return new global::LightSwitchApplication.Implementation.t_tipoviolencia();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_usItem))
            {
                return new global::LightSwitchApplication.Implementation.t_usItem();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.t_user))
            {
                return new global::LightSwitchApplication.Implementation.t_user();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.tratamentotb))
            {
                return new global::LightSwitchApplication.Implementation.tratamentotb();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.usuario))
            {
                return new global::LightSwitchApplication.Implementation.usuario();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.dbmanualsourceData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.dbmanualsourceData(this.GetEntityConnectionString(
                "dbmanualsourceData",
                "res://" + assemblyName + "/dbmanualsourceData.csdl|res://" + assemblyName + "/dbmanualsourceData.ssdl|res://" + assemblyName + "/dbmanualsourceData.msl",
                "MySql.Data.MySqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.amostrastb))
            {
                return new global::LightSwitchApplication.Implementation.amostrastb();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ccr))
            {
                return new global::LightSwitchApplication.Implementation.ccr();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ccrseg))
            {
                return new global::LightSwitchApplication.Implementation.ccrseg();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.child))
            {
                return new global::LightSwitchApplication.Implementation.child();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.cpn_final))
            {
                return new global::LightSwitchApplication.Implementation.cpn_final();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.cpn))
            {
                return new global::LightSwitchApplication.Implementation.cpn();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.cpp))
            {
                return new global::LightSwitchApplication.Implementation.cpp();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.csr_pf))
            {
                return new global::LightSwitchApplication.Implementation.csr_pf();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.laboratoriotb))
            {
                return new global::LightSwitchApplication.Implementation.laboratoriotb();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.livro))
            {
                return new global::LightSwitchApplication.Implementation.livro();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.maternidade))
            {
                return new global::LightSwitchApplication.Implementation.maternidade();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.mother))
            {
                return new global::LightSwitchApplication.Implementation.mother();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.paciente_resistente_tb))
            {
                return new global::LightSwitchApplication.Implementation.paciente_resistente_tb();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.pacientetb))
            {
                return new global::LightSwitchApplication.Implementation.pacientetb();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.patient))
            {
                return new global::LightSwitchApplication.Implementation.patient();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_categoria))
            {
                return new global::LightSwitchApplication.Implementation.t_categoria();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_grauexposicao))
            {
                return new global::LightSwitchApplication.Implementation.t_grauexposicao();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_historia_clinica_notificacao))
            {
                return new global::LightSwitchApplication.Implementation.t_historia_clinica_notificacao();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_historiaclinica))
            {
                return new global::LightSwitchApplication.Implementation.t_historiaclinica();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_intervenco))
            {
                return new global::LightSwitchApplication.Implementation.t_intervenco();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_laboratorio_notificacao))
            {
                return new global::LightSwitchApplication.Implementation.t_laboratorio_notificacao();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_localacidente))
            {
                return new global::LightSwitchApplication.Implementation.t_localacidente();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_notificacao))
            {
                return new global::LightSwitchApplication.Implementation.t_notificacao();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_referencia))
            {
                return new global::LightSwitchApplication.Implementation.t_referencia();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_referido))
            {
                return new global::LightSwitchApplication.Implementation.t_referido();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_regimeppe))
            {
                return new global::LightSwitchApplication.Implementation.t_regimeppe();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_registodiarioppe))
            {
                return new global::LightSwitchApplication.Implementation.t_registodiarioppe();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_registodiariovgb))
            {
                return new global::LightSwitchApplication.Implementation.t_registodiariovgb();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_resultadosppe))
            {
                return new global::LightSwitchApplication.Implementation.t_resultadosppe();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_resultadoteste))
            {
                return new global::LightSwitchApplication.Implementation.t_resultadoteste();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_seguimento_notificacao))
            {
                return new global::LightSwitchApplication.Implementation.t_seguimento_notificacao();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_tipoviolencia))
            {
                return new global::LightSwitchApplication.Implementation.t_tipoviolencia();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_usItem))
            {
                return new global::LightSwitchApplication.Implementation.t_usItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.t_user))
            {
                return new global::LightSwitchApplication.Implementation.t_user();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.tratamentotb))
            {
                return new global::LightSwitchApplication.Implementation.tratamentotb();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.usuario))
            {
                return new global::LightSwitchApplication.Implementation.usuario();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            if (dataServiceType == typeof(global::LightSwitchApplication.dbmanualsourceDataService))
            {
                return new global::LightSwitchApplication.dbmanualsourceDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.dbmanualsourceDataService))
            {
                return new global::LightSwitchApplication.Implementation.dbmanualsourceDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.amostrastb) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.amostrastb);
            }
            if (typeof(global::LightSwitchApplication.ccr) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ccr);
            }
            if (typeof(global::LightSwitchApplication.ccrseg) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ccrseg);
            }
            if (typeof(global::LightSwitchApplication.child) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.child);
            }
            if (typeof(global::LightSwitchApplication.cpn_final) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.cpn_final);
            }
            if (typeof(global::LightSwitchApplication.cpn) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.cpn);
            }
            if (typeof(global::LightSwitchApplication.cpp) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.cpp);
            }
            if (typeof(global::LightSwitchApplication.csr_pf) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.csr_pf);
            }
            if (typeof(global::LightSwitchApplication.laboratoriotb) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.laboratoriotb);
            }
            if (typeof(global::LightSwitchApplication.livro) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.livro);
            }
            if (typeof(global::LightSwitchApplication.maternidade) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.maternidade);
            }
            if (typeof(global::LightSwitchApplication.mother) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.mother);
            }
            if (typeof(global::LightSwitchApplication.paciente_resistente_tb) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.paciente_resistente_tb);
            }
            if (typeof(global::LightSwitchApplication.pacientetb) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.pacientetb);
            }
            if (typeof(global::LightSwitchApplication.patient) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.patient);
            }
            if (typeof(global::LightSwitchApplication.t_categoria) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_categoria);
            }
            if (typeof(global::LightSwitchApplication.t_grauexposicao) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_grauexposicao);
            }
            if (typeof(global::LightSwitchApplication.t_historia_clinica_notificacao) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_historia_clinica_notificacao);
            }
            if (typeof(global::LightSwitchApplication.t_historiaclinica) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_historiaclinica);
            }
            if (typeof(global::LightSwitchApplication.t_intervenco) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_intervenco);
            }
            if (typeof(global::LightSwitchApplication.t_laboratorio_notificacao) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_laboratorio_notificacao);
            }
            if (typeof(global::LightSwitchApplication.t_localacidente) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_localacidente);
            }
            if (typeof(global::LightSwitchApplication.t_notificacao) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_notificacao);
            }
            if (typeof(global::LightSwitchApplication.t_referencia) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_referencia);
            }
            if (typeof(global::LightSwitchApplication.t_referido) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_referido);
            }
            if (typeof(global::LightSwitchApplication.t_regimeppe) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_regimeppe);
            }
            if (typeof(global::LightSwitchApplication.t_registodiarioppe) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_registodiarioppe);
            }
            if (typeof(global::LightSwitchApplication.t_registodiariovgb) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_registodiariovgb);
            }
            if (typeof(global::LightSwitchApplication.t_resultadosppe) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_resultadosppe);
            }
            if (typeof(global::LightSwitchApplication.t_resultadoteste) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_resultadoteste);
            }
            if (typeof(global::LightSwitchApplication.t_seguimento_notificacao) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_seguimento_notificacao);
            }
            if (typeof(global::LightSwitchApplication.t_tipoviolencia) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_tipoviolencia);
            }
            if (typeof(global::LightSwitchApplication.t_usItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_usItem);
            }
            if (typeof(global::LightSwitchApplication.t_user) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.t_user);
            }
            if (typeof(global::LightSwitchApplication.tratamentotb) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.tratamentotb);
            }
            if (typeof(global::LightSwitchApplication.usuario) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.usuario);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class amostrastb :
        global::LightSwitchApplication.amostrastb.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ccr :
        global::LightSwitchApplication.ccr.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ccr.DetailsClass.IImplementation.ccrsegs
        {
            get
            {
                return this.ccrsegs;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ccr.DetailsClass.IImplementation.child
        {
            get
            {
                return this.child;
            }
            set
            {
                this.child = (global::LightSwitchApplication.Implementation.child)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("child");
                }
            }
        }
        
        partial void OnidchildChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("child");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ccrseg :
        global::LightSwitchApplication.ccrseg.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ccrseg.DetailsClass.IImplementation.ccr
        {
            get
            {
                return this.ccr;
            }
            set
            {
                this.ccr = (global::LightSwitchApplication.Implementation.ccr)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ccr");
                }
            }
        }
        
        partial void OnidccrChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ccr");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class child :
        global::LightSwitchApplication.child.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.child.DetailsClass.IImplementation.ccrs
        {
            get
            {
                return this.ccrs;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.child.DetailsClass.IImplementation.mother
        {
            get
            {
                return this.mother;
            }
            set
            {
                this.mother = (global::LightSwitchApplication.Implementation.mother)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("mother");
                }
            }
        }
        
        partial void Onid_motherChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("mother");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class cpn_final :
        global::LightSwitchApplication.cpn_final.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class cpn :
        global::LightSwitchApplication.cpn.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.cpn.DetailsClass.IImplementation.mother
        {
            get
            {
                return this.mother;
            }
            set
            {
                this.mother = (global::LightSwitchApplication.Implementation.mother)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("mother");
                }
            }
        }
        
        partial void OnidmotherChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("mother");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class cpp :
        global::LightSwitchApplication.cpp.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class csr_pf :
        global::LightSwitchApplication.csr_pf.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class laboratoriotb :
        global::LightSwitchApplication.laboratoriotb.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class livro :
        global::LightSwitchApplication.livro.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class maternidade :
        global::LightSwitchApplication.maternidade.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class mother :
        global::LightSwitchApplication.mother.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.mother.DetailsClass.IImplementation.children
        {
            get
            {
                return this.children;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.mother.DetailsClass.IImplementation.cpns
        {
            get
            {
                return this.cpns;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class paciente_resistente_tb :
        global::LightSwitchApplication.paciente_resistente_tb.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class pacientetb :
        global::LightSwitchApplication.pacientetb.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class patient :
        global::LightSwitchApplication.patient.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_categoria :
        global::LightSwitchApplication.t_categoria.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_grauexposicao :
        global::LightSwitchApplication.t_grauexposicao.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_historia_clinica_notificacao :
        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_historiaclinica :
        global::LightSwitchApplication.t_historiaclinica.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_intervenco :
        global::LightSwitchApplication.t_intervenco.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_laboratorio_notificacao :
        global::LightSwitchApplication.t_laboratorio_notificacao.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_localacidente :
        global::LightSwitchApplication.t_localacidente.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_notificacao :
        global::LightSwitchApplication.t_notificacao.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_referencia :
        global::LightSwitchApplication.t_referencia.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_referido :
        global::LightSwitchApplication.t_referido.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_regimeppe :
        global::LightSwitchApplication.t_regimeppe.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_registodiarioppe :
        global::LightSwitchApplication.t_registodiarioppe.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_registodiariovgb :
        global::LightSwitchApplication.t_registodiariovgb.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_resultadosppe :
        global::LightSwitchApplication.t_resultadosppe.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_resultadoteste :
        global::LightSwitchApplication.t_resultadoteste.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_seguimento_notificacao :
        global::LightSwitchApplication.t_seguimento_notificacao.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_tipoviolencia :
        global::LightSwitchApplication.t_tipoviolencia.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_usItem :
        global::LightSwitchApplication.t_usItem.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class t_user :
        global::LightSwitchApplication.t_user.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class tratamentotb :
        global::LightSwitchApplication.tratamentotb.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class usuario :
        global::LightSwitchApplication.usuario.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

