

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class t_referido : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the t_referido entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_referido()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_referido(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_referido> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.t_referido.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_referido_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_referido_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int codreferido
        {
            get
            {
                return global::LightSwitchApplication.t_referido.DetailsClass.GetValue(this, global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties.codreferido);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codreferido_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codreferido_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codreferido_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string referido
        {
            get
            {
                return global::LightSwitchApplication.t_referido.DetailsClass.GetValue(this, global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties.referido);
            }
            set
            {
                global::LightSwitchApplication.t_referido.DetailsClass.SetValue(this, global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties.referido, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void referido_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void referido_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void referido_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.t_referido,
                global::LightSwitchApplication.t_referido.DetailsClass,
                global::LightSwitchApplication.t_referido.DetailsClass.IImplementation,
                global::LightSwitchApplication.t_referido.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties.codreferido;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass>.Entry
                __t_referidoEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass>.Entry(
                    global::LightSwitchApplication.t_referido.DetailsClass.__t_referido_CreateNew,
                    global::LightSwitchApplication.t_referido.DetailsClass.__t_referido_Created,
                    global::LightSwitchApplication.t_referido.DetailsClass.__t_referido_AllowSaveWithErrors);
            private static global::LightSwitchApplication.t_referido __t_referido_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_referido> es)
            {
                return new global::LightSwitchApplication.t_referido(es);
            }
            private static void __t_referido_Created(global::LightSwitchApplication.t_referido e)
            {
                e.t_referido_Created();
            }
            private static bool __t_referido_AllowSaveWithErrors(global::LightSwitchApplication.t_referido e)
            {
                bool result = false;
                e.t_referido_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.t_referido.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass, int> codreferido
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties.codreferido) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass, string> referido
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties.referido) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int codreferido { get; }
                new string referido { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass, int>.Entry
                    codreferido = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass, int>.Entry(
                        "codreferido",
                        global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties._codreferido_Stub,
                        global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties._codreferido_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties._codreferido_Validate,
                        global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties._codreferido_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties._codreferido_OnValueChanged);
                private static void _codreferido_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_referido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass, int>.Data> c, global::LightSwitchApplication.t_referido.DetailsClass d, object sf)
                {
                    c(d, ref d._codreferido, sf);
                }
                private static bool _codreferido_ComputeIsReadOnly(global::LightSwitchApplication.t_referido e)
                {
                    bool result = false;
                    e.codreferido_IsReadOnly(ref result);
                    return result;
                }
                private static void _codreferido_Validate(global::LightSwitchApplication.t_referido e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.codreferido_Validate(r);
                }
                private static int _codreferido_GetImplementationValue(global::LightSwitchApplication.t_referido.DetailsClass d)
                {
                    return d.ImplementationEntity.codreferido;
                }
                private static void _codreferido_OnValueChanged(global::LightSwitchApplication.t_referido e)
                {
                    e.codreferido_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass, string>.Entry
                    referido = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass, string>.Entry(
                        "referido",
                        global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties._referido_Stub,
                        global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties._referido_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties._referido_Validate,
                        global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties._referido_GetImplementationValue,
                        global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties._referido_SetImplementationValue,
                        global::LightSwitchApplication.t_referido.DetailsClass.PropertySetProperties._referido_OnValueChanged);
                private static void _referido_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_referido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_referido.DetailsClass d, object sf)
                {
                    c(d, ref d._referido, sf);
                }
                private static bool _referido_ComputeIsReadOnly(global::LightSwitchApplication.t_referido e)
                {
                    bool result = false;
                    e.referido_IsReadOnly(ref result);
                    return result;
                }
                private static void _referido_Validate(global::LightSwitchApplication.t_referido e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.referido_Validate(r);
                }
                private static string _referido_GetImplementationValue(global::LightSwitchApplication.t_referido.DetailsClass d)
                {
                    return d.ImplementationEntity.referido;
                }
                private static void _referido_SetImplementationValue(global::LightSwitchApplication.t_referido.DetailsClass d, string v)
                {
                    d.ImplementationEntity.referido = v;
                }
                private static void _referido_OnValueChanged(global::LightSwitchApplication.t_referido e)
                {
                    e.referido_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass, int>.Data _codreferido;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_referido, global::LightSwitchApplication.t_referido.DetailsClass, string>.Data _referido;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class t_regimeppe : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the t_regimeppe entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_regimeppe()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_regimeppe(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_regimeppe> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.t_regimeppe.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_regimeppe_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_regimeppe_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int codigo
        {
            get
            {
                return global::LightSwitchApplication.t_regimeppe.DetailsClass.GetValue(this, global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties.codigo);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codigo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codigo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codigo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string regime
        {
            get
            {
                return global::LightSwitchApplication.t_regimeppe.DetailsClass.GetValue(this, global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties.regime);
            }
            set
            {
                global::LightSwitchApplication.t_regimeppe.DetailsClass.SetValue(this, global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties.regime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void regime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void regime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void regime_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.t_regimeppe,
                global::LightSwitchApplication.t_regimeppe.DetailsClass,
                global::LightSwitchApplication.t_regimeppe.DetailsClass.IImplementation,
                global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties.codigo;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass>.Entry
                __t_regimeppeEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass>.Entry(
                    global::LightSwitchApplication.t_regimeppe.DetailsClass.__t_regimeppe_CreateNew,
                    global::LightSwitchApplication.t_regimeppe.DetailsClass.__t_regimeppe_Created,
                    global::LightSwitchApplication.t_regimeppe.DetailsClass.__t_regimeppe_AllowSaveWithErrors);
            private static global::LightSwitchApplication.t_regimeppe __t_regimeppe_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_regimeppe> es)
            {
                return new global::LightSwitchApplication.t_regimeppe(es);
            }
            private static void __t_regimeppe_Created(global::LightSwitchApplication.t_regimeppe e)
            {
                e.t_regimeppe_Created();
            }
            private static bool __t_regimeppe_AllowSaveWithErrors(global::LightSwitchApplication.t_regimeppe e)
            {
                bool result = false;
                e.t_regimeppe_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass, int> codigo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties.codigo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass, string> regime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties.regime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int codigo { get; }
                new string regime { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass, int>.Entry
                    codigo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass, int>.Entry(
                        "codigo",
                        global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties._codigo_Stub,
                        global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties._codigo_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties._codigo_Validate,
                        global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties._codigo_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties._codigo_OnValueChanged);
                private static void _codigo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_regimeppe.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass, int>.Data> c, global::LightSwitchApplication.t_regimeppe.DetailsClass d, object sf)
                {
                    c(d, ref d._codigo, sf);
                }
                private static bool _codigo_ComputeIsReadOnly(global::LightSwitchApplication.t_regimeppe e)
                {
                    bool result = false;
                    e.codigo_IsReadOnly(ref result);
                    return result;
                }
                private static void _codigo_Validate(global::LightSwitchApplication.t_regimeppe e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.codigo_Validate(r);
                }
                private static int _codigo_GetImplementationValue(global::LightSwitchApplication.t_regimeppe.DetailsClass d)
                {
                    return d.ImplementationEntity.codigo;
                }
                private static void _codigo_OnValueChanged(global::LightSwitchApplication.t_regimeppe e)
                {
                    e.codigo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass, string>.Entry
                    regime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass, string>.Entry(
                        "regime",
                        global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties._regime_Stub,
                        global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties._regime_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties._regime_Validate,
                        global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties._regime_GetImplementationValue,
                        global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties._regime_SetImplementationValue,
                        global::LightSwitchApplication.t_regimeppe.DetailsClass.PropertySetProperties._regime_OnValueChanged);
                private static void _regime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_regimeppe.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_regimeppe.DetailsClass d, object sf)
                {
                    c(d, ref d._regime, sf);
                }
                private static bool _regime_ComputeIsReadOnly(global::LightSwitchApplication.t_regimeppe e)
                {
                    bool result = false;
                    e.regime_IsReadOnly(ref result);
                    return result;
                }
                private static void _regime_Validate(global::LightSwitchApplication.t_regimeppe e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.regime_Validate(r);
                }
                private static string _regime_GetImplementationValue(global::LightSwitchApplication.t_regimeppe.DetailsClass d)
                {
                    return d.ImplementationEntity.regime;
                }
                private static void _regime_SetImplementationValue(global::LightSwitchApplication.t_regimeppe.DetailsClass d, string v)
                {
                    d.ImplementationEntity.regime = v;
                }
                private static void _regime_OnValueChanged(global::LightSwitchApplication.t_regimeppe e)
                {
                    e.regime_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass, int>.Data _codigo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_regimeppe, global::LightSwitchApplication.t_regimeppe.DetailsClass, string>.Data _regime;
            
        }
    
        #endregion
    }
    
    #endregion
}
