

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class t_usItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the t_usItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_usItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_usItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_usItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.t_usItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_usItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_usItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int id
        {
            get
            {
                return global::LightSwitchApplication.t_usItem.DetailsClass.GetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string codigo
        {
            get
            {
                return global::LightSwitchApplication.t_usItem.DetailsClass.GetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.codigo);
            }
            set
            {
                global::LightSwitchApplication.t_usItem.DetailsClass.SetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.codigo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codigo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codigo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codigo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string designacao
        {
            get
            {
                return global::LightSwitchApplication.t_usItem.DetailsClass.GetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.designacao);
            }
            set
            {
                global::LightSwitchApplication.t_usItem.DetailsClass.SetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.designacao, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void designacao_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void designacao_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void designacao_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string distrito
        {
            get
            {
                return global::LightSwitchApplication.t_usItem.DetailsClass.GetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.distrito);
            }
            set
            {
                global::LightSwitchApplication.t_usItem.DetailsClass.SetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.distrito, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void distrito_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void distrito_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void distrito_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string localidade
        {
            get
            {
                return global::LightSwitchApplication.t_usItem.DetailsClass.GetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.localidade);
            }
            set
            {
                global::LightSwitchApplication.t_usItem.DetailsClass.SetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.localidade, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void localidade_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void localidade_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void localidade_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> activo
        {
            get
            {
                return global::LightSwitchApplication.t_usItem.DetailsClass.GetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.activo);
            }
            set
            {
                global::LightSwitchApplication.t_usItem.DetailsClass.SetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.activo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void activo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void activo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void activo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string provincia
        {
            get
            {
                return global::LightSwitchApplication.t_usItem.DetailsClass.GetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.provincia);
            }
            set
            {
                global::LightSwitchApplication.t_usItem.DetailsClass.SetValue(this, global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.provincia, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void provincia_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void provincia_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void provincia_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.t_usItem,
                global::LightSwitchApplication.t_usItem.DetailsClass,
                global::LightSwitchApplication.t_usItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.t_usItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass>.Entry
                __t_usItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.t_usItem.DetailsClass.__t_usItem_CreateNew,
                    global::LightSwitchApplication.t_usItem.DetailsClass.__t_usItem_Created,
                    global::LightSwitchApplication.t_usItem.DetailsClass.__t_usItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.t_usItem __t_usItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_usItem> es)
            {
                return new global::LightSwitchApplication.t_usItem(es);
            }
            private static void __t_usItem_Created(global::LightSwitchApplication.t_usItem e)
            {
                e.t_usItem_Created();
            }
            private static bool __t_usItem_AllowSaveWithErrors(global::LightSwitchApplication.t_usItem e)
            {
                bool result = false;
                e.t_usItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.t_usItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, int> id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string> codigo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.codigo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string> designacao
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.designacao) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string> distrito
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.distrito) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string> localidade
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.localidade) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, global::System.Nullable<bool>> activo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.activo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string> provincia
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties.provincia) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int id { get; }
                new string codigo { get; set; }
                new string designacao { get; set; }
                new string distrito { get; set; }
                new string localidade { get; set; }
                new global::System.Nullable<bool> activo { get; set; }
                new string provincia { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, int>.Entry
                    id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, int>.Entry(
                        "id",
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._id_Stub,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._id_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._id_Validate,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._id_OnValueChanged);
                private static void _id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_usItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.t_usItem.DetailsClass d, object sf)
                {
                    c(d, ref d._id, sf);
                }
                private static bool _id_ComputeIsReadOnly(global::LightSwitchApplication.t_usItem e)
                {
                    bool result = false;
                    e.id_IsReadOnly(ref result);
                    return result;
                }
                private static void _id_Validate(global::LightSwitchApplication.t_usItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.id_Validate(r);
                }
                private static int _id_GetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d)
                {
                    return d.ImplementationEntity.id;
                }
                private static void _id_OnValueChanged(global::LightSwitchApplication.t_usItem e)
                {
                    e.id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Entry
                    codigo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Entry(
                        "codigo",
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._codigo_Stub,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._codigo_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._codigo_Validate,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._codigo_GetImplementationValue,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._codigo_SetImplementationValue,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._codigo_OnValueChanged);
                private static void _codigo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_usItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_usItem.DetailsClass d, object sf)
                {
                    c(d, ref d._codigo, sf);
                }
                private static bool _codigo_ComputeIsReadOnly(global::LightSwitchApplication.t_usItem e)
                {
                    bool result = false;
                    e.codigo_IsReadOnly(ref result);
                    return result;
                }
                private static void _codigo_Validate(global::LightSwitchApplication.t_usItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.codigo_Validate(r);
                }
                private static string _codigo_GetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d)
                {
                    return d.ImplementationEntity.codigo;
                }
                private static void _codigo_SetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.codigo = v;
                }
                private static void _codigo_OnValueChanged(global::LightSwitchApplication.t_usItem e)
                {
                    e.codigo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Entry
                    designacao = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Entry(
                        "designacao",
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._designacao_Stub,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._designacao_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._designacao_Validate,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._designacao_GetImplementationValue,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._designacao_SetImplementationValue,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._designacao_OnValueChanged);
                private static void _designacao_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_usItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_usItem.DetailsClass d, object sf)
                {
                    c(d, ref d._designacao, sf);
                }
                private static bool _designacao_ComputeIsReadOnly(global::LightSwitchApplication.t_usItem e)
                {
                    bool result = false;
                    e.designacao_IsReadOnly(ref result);
                    return result;
                }
                private static void _designacao_Validate(global::LightSwitchApplication.t_usItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.designacao_Validate(r);
                }
                private static string _designacao_GetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d)
                {
                    return d.ImplementationEntity.designacao;
                }
                private static void _designacao_SetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.designacao = v;
                }
                private static void _designacao_OnValueChanged(global::LightSwitchApplication.t_usItem e)
                {
                    e.designacao_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Entry
                    distrito = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Entry(
                        "distrito",
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._distrito_Stub,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._distrito_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._distrito_Validate,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._distrito_GetImplementationValue,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._distrito_SetImplementationValue,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._distrito_OnValueChanged);
                private static void _distrito_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_usItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_usItem.DetailsClass d, object sf)
                {
                    c(d, ref d._distrito, sf);
                }
                private static bool _distrito_ComputeIsReadOnly(global::LightSwitchApplication.t_usItem e)
                {
                    bool result = false;
                    e.distrito_IsReadOnly(ref result);
                    return result;
                }
                private static void _distrito_Validate(global::LightSwitchApplication.t_usItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.distrito_Validate(r);
                }
                private static string _distrito_GetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d)
                {
                    return d.ImplementationEntity.distrito;
                }
                private static void _distrito_SetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.distrito = v;
                }
                private static void _distrito_OnValueChanged(global::LightSwitchApplication.t_usItem e)
                {
                    e.distrito_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Entry
                    localidade = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Entry(
                        "localidade",
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._localidade_Stub,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._localidade_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._localidade_Validate,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._localidade_GetImplementationValue,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._localidade_SetImplementationValue,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._localidade_OnValueChanged);
                private static void _localidade_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_usItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_usItem.DetailsClass d, object sf)
                {
                    c(d, ref d._localidade, sf);
                }
                private static bool _localidade_ComputeIsReadOnly(global::LightSwitchApplication.t_usItem e)
                {
                    bool result = false;
                    e.localidade_IsReadOnly(ref result);
                    return result;
                }
                private static void _localidade_Validate(global::LightSwitchApplication.t_usItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.localidade_Validate(r);
                }
                private static string _localidade_GetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d)
                {
                    return d.ImplementationEntity.localidade;
                }
                private static void _localidade_SetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.localidade = v;
                }
                private static void _localidade_OnValueChanged(global::LightSwitchApplication.t_usItem e)
                {
                    e.localidade_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, global::System.Nullable<bool>>.Entry
                    activo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "activo",
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._activo_Stub,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._activo_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._activo_Validate,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._activo_GetImplementationValue,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._activo_SetImplementationValue,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._activo_OnValueChanged);
                private static void _activo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_usItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.t_usItem.DetailsClass d, object sf)
                {
                    c(d, ref d._activo, sf);
                }
                private static bool _activo_ComputeIsReadOnly(global::LightSwitchApplication.t_usItem e)
                {
                    bool result = false;
                    e.activo_IsReadOnly(ref result);
                    return result;
                }
                private static void _activo_Validate(global::LightSwitchApplication.t_usItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.activo_Validate(r);
                }
                private static global::System.Nullable<bool> _activo_GetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d)
                {
                    return d.ImplementationEntity.activo;
                }
                private static void _activo_SetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.activo = v;
                }
                private static void _activo_OnValueChanged(global::LightSwitchApplication.t_usItem e)
                {
                    e.activo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Entry
                    provincia = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Entry(
                        "provincia",
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._provincia_Stub,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._provincia_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._provincia_Validate,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._provincia_GetImplementationValue,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._provincia_SetImplementationValue,
                        global::LightSwitchApplication.t_usItem.DetailsClass.PropertySetProperties._provincia_OnValueChanged);
                private static void _provincia_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_usItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_usItem.DetailsClass d, object sf)
                {
                    c(d, ref d._provincia, sf);
                }
                private static bool _provincia_ComputeIsReadOnly(global::LightSwitchApplication.t_usItem e)
                {
                    bool result = false;
                    e.provincia_IsReadOnly(ref result);
                    return result;
                }
                private static void _provincia_Validate(global::LightSwitchApplication.t_usItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.provincia_Validate(r);
                }
                private static string _provincia_GetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d)
                {
                    return d.ImplementationEntity.provincia;
                }
                private static void _provincia_SetImplementationValue(global::LightSwitchApplication.t_usItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.provincia = v;
                }
                private static void _provincia_OnValueChanged(global::LightSwitchApplication.t_usItem e)
                {
                    e.provincia_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, int>.Data _id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Data _codigo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Data _designacao;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Data _distrito;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Data _localidade;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, global::System.Nullable<bool>>.Data _activo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_usItem, global::LightSwitchApplication.t_usItem.DetailsClass, string>.Data _provincia;
            
        }
    
        #endregion
    }
    
    #endregion
}
