

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class t_grauexposicao : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the t_grauexposicao entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_grauexposicao()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_grauexposicao(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_grauexposicao> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.t_grauexposicao.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_grauexposicao_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_grauexposicao_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int codigo
        {
            get
            {
                return global::LightSwitchApplication.t_grauexposicao.DetailsClass.GetValue(this, global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties.codigo);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codigo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codigo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codigo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string grauexposicao
        {
            get
            {
                return global::LightSwitchApplication.t_grauexposicao.DetailsClass.GetValue(this, global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties.grauexposicao);
            }
            set
            {
                global::LightSwitchApplication.t_grauexposicao.DetailsClass.SetValue(this, global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties.grauexposicao, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void grauexposicao_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void grauexposicao_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void grauexposicao_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.t_grauexposicao,
                global::LightSwitchApplication.t_grauexposicao.DetailsClass,
                global::LightSwitchApplication.t_grauexposicao.DetailsClass.IImplementation,
                global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties.codigo;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass>.Entry
                __t_grauexposicaoEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass>.Entry(
                    global::LightSwitchApplication.t_grauexposicao.DetailsClass.__t_grauexposicao_CreateNew,
                    global::LightSwitchApplication.t_grauexposicao.DetailsClass.__t_grauexposicao_Created,
                    global::LightSwitchApplication.t_grauexposicao.DetailsClass.__t_grauexposicao_AllowSaveWithErrors);
            private static global::LightSwitchApplication.t_grauexposicao __t_grauexposicao_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_grauexposicao> es)
            {
                return new global::LightSwitchApplication.t_grauexposicao(es);
            }
            private static void __t_grauexposicao_Created(global::LightSwitchApplication.t_grauexposicao e)
            {
                e.t_grauexposicao_Created();
            }
            private static bool __t_grauexposicao_AllowSaveWithErrors(global::LightSwitchApplication.t_grauexposicao e)
            {
                bool result = false;
                e.t_grauexposicao_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass, int> codigo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties.codigo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass, string> grauexposicao
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties.grauexposicao) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int codigo { get; }
                new string grauexposicao { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass, int>.Entry
                    codigo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass, int>.Entry(
                        "codigo",
                        global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties._codigo_Stub,
                        global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties._codigo_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties._codigo_Validate,
                        global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties._codigo_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties._codigo_OnValueChanged);
                private static void _codigo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_grauexposicao.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass, int>.Data> c, global::LightSwitchApplication.t_grauexposicao.DetailsClass d, object sf)
                {
                    c(d, ref d._codigo, sf);
                }
                private static bool _codigo_ComputeIsReadOnly(global::LightSwitchApplication.t_grauexposicao e)
                {
                    bool result = false;
                    e.codigo_IsReadOnly(ref result);
                    return result;
                }
                private static void _codigo_Validate(global::LightSwitchApplication.t_grauexposicao e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.codigo_Validate(r);
                }
                private static int _codigo_GetImplementationValue(global::LightSwitchApplication.t_grauexposicao.DetailsClass d)
                {
                    return d.ImplementationEntity.codigo;
                }
                private static void _codigo_OnValueChanged(global::LightSwitchApplication.t_grauexposicao e)
                {
                    e.codigo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass, string>.Entry
                    grauexposicao = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass, string>.Entry(
                        "grauexposicao",
                        global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties._grauexposicao_Stub,
                        global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties._grauexposicao_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties._grauexposicao_Validate,
                        global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties._grauexposicao_GetImplementationValue,
                        global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties._grauexposicao_SetImplementationValue,
                        global::LightSwitchApplication.t_grauexposicao.DetailsClass.PropertySetProperties._grauexposicao_OnValueChanged);
                private static void _grauexposicao_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_grauexposicao.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_grauexposicao.DetailsClass d, object sf)
                {
                    c(d, ref d._grauexposicao, sf);
                }
                private static bool _grauexposicao_ComputeIsReadOnly(global::LightSwitchApplication.t_grauexposicao e)
                {
                    bool result = false;
                    e.grauexposicao_IsReadOnly(ref result);
                    return result;
                }
                private static void _grauexposicao_Validate(global::LightSwitchApplication.t_grauexposicao e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.grauexposicao_Validate(r);
                }
                private static string _grauexposicao_GetImplementationValue(global::LightSwitchApplication.t_grauexposicao.DetailsClass d)
                {
                    return d.ImplementationEntity.grauexposicao;
                }
                private static void _grauexposicao_SetImplementationValue(global::LightSwitchApplication.t_grauexposicao.DetailsClass d, string v)
                {
                    d.ImplementationEntity.grauexposicao = v;
                }
                private static void _grauexposicao_OnValueChanged(global::LightSwitchApplication.t_grauexposicao e)
                {
                    e.grauexposicao_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass, int>.Data _codigo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_grauexposicao, global::LightSwitchApplication.t_grauexposicao.DetailsClass, string>.Data _grauexposicao;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class t_historia_clinica_notificacao : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the t_historia_clinica_notificacao entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_historia_clinica_notificacao()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_historia_clinica_notificacao(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_historia_clinica_notificacao> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_historia_clinica_notificacao_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_historia_clinica_notificacao_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ordem
        {
            get
            {
                return global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.GetValue(this, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.ordem);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ordem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ordem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ordem_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string notificacao
        {
            get
            {
                return global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.GetValue(this, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.notificacao);
            }
            set
            {
                global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.SetValue(this, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.notificacao, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void notificacao_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void notificacao_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void notificacao_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> id
        {
            get
            {
                return global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.GetValue(this, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.id);
            }
            set
            {
                global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.SetValue(this, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string historicoclinico
        {
            get
            {
                return global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.GetValue(this, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.historicoclinico);
            }
            set
            {
                global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.SetValue(this, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.historicoclinico, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void historicoclinico_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void historicoclinico_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void historicoclinico_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> valor
        {
            get
            {
                return global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.GetValue(this, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.valor);
            }
            set
            {
                global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.SetValue(this, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.valor, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void valor_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void valor_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void valor_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.t_historia_clinica_notificacao,
                global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass,
                global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.IImplementation,
                global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.ordem;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass>.Entry
                __t_historia_clinica_notificacaoEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass>.Entry(
                    global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.__t_historia_clinica_notificacao_CreateNew,
                    global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.__t_historia_clinica_notificacao_Created,
                    global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.__t_historia_clinica_notificacao_AllowSaveWithErrors);
            private static global::LightSwitchApplication.t_historia_clinica_notificacao __t_historia_clinica_notificacao_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_historia_clinica_notificacao> es)
            {
                return new global::LightSwitchApplication.t_historia_clinica_notificacao(es);
            }
            private static void __t_historia_clinica_notificacao_Created(global::LightSwitchApplication.t_historia_clinica_notificacao e)
            {
                e.t_historia_clinica_notificacao_Created();
            }
            private static bool __t_historia_clinica_notificacao_AllowSaveWithErrors(global::LightSwitchApplication.t_historia_clinica_notificacao e)
            {
                bool result = false;
                e.t_historia_clinica_notificacao_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, int> ordem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.ordem) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, string> notificacao
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.notificacao) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::System.Nullable<int>> id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, string> historicoclinico
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.historicoclinico) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::System.Nullable<bool>> valor
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties.valor) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ordem { get; }
                new string notificacao { get; set; }
                new global::System.Nullable<int> id { get; set; }
                new string historicoclinico { get; set; }
                new global::System.Nullable<bool> valor { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, int>.Entry
                    ordem = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, int>.Entry(
                        "ordem",
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._ordem_Stub,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._ordem_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._ordem_Validate,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._ordem_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._ordem_OnValueChanged);
                private static void _ordem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, int>.Data> c, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d, object sf)
                {
                    c(d, ref d._ordem, sf);
                }
                private static bool _ordem_ComputeIsReadOnly(global::LightSwitchApplication.t_historia_clinica_notificacao e)
                {
                    bool result = false;
                    e.ordem_IsReadOnly(ref result);
                    return result;
                }
                private static void _ordem_Validate(global::LightSwitchApplication.t_historia_clinica_notificacao e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ordem_Validate(r);
                }
                private static int _ordem_GetImplementationValue(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d)
                {
                    return d.ImplementationEntity.ordem;
                }
                private static void _ordem_OnValueChanged(global::LightSwitchApplication.t_historia_clinica_notificacao e)
                {
                    e.ordem_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, string>.Entry
                    notificacao = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, string>.Entry(
                        "notificacao",
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._notificacao_Stub,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._notificacao_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._notificacao_Validate,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._notificacao_GetImplementationValue,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._notificacao_SetImplementationValue,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._notificacao_OnValueChanged);
                private static void _notificacao_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d, object sf)
                {
                    c(d, ref d._notificacao, sf);
                }
                private static bool _notificacao_ComputeIsReadOnly(global::LightSwitchApplication.t_historia_clinica_notificacao e)
                {
                    bool result = false;
                    e.notificacao_IsReadOnly(ref result);
                    return result;
                }
                private static void _notificacao_Validate(global::LightSwitchApplication.t_historia_clinica_notificacao e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.notificacao_Validate(r);
                }
                private static string _notificacao_GetImplementationValue(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d)
                {
                    return d.ImplementationEntity.notificacao;
                }
                private static void _notificacao_SetImplementationValue(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d, string v)
                {
                    d.ImplementationEntity.notificacao = v;
                }
                private static void _notificacao_OnValueChanged(global::LightSwitchApplication.t_historia_clinica_notificacao e)
                {
                    e.notificacao_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::System.Nullable<int>>.Entry
                    id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::System.Nullable<int>>.Entry(
                        "id",
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._id_Stub,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._id_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._id_Validate,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._id_GetImplementationValue,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._id_SetImplementationValue,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._id_OnValueChanged);
                private static void _id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d, object sf)
                {
                    c(d, ref d._id, sf);
                }
                private static bool _id_ComputeIsReadOnly(global::LightSwitchApplication.t_historia_clinica_notificacao e)
                {
                    bool result = false;
                    e.id_IsReadOnly(ref result);
                    return result;
                }
                private static void _id_Validate(global::LightSwitchApplication.t_historia_clinica_notificacao e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.id_Validate(r);
                }
                private static global::System.Nullable<int> _id_GetImplementationValue(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d)
                {
                    return d.ImplementationEntity.id;
                }
                private static void _id_SetImplementationValue(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.id = v;
                }
                private static void _id_OnValueChanged(global::LightSwitchApplication.t_historia_clinica_notificacao e)
                {
                    e.id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, string>.Entry
                    historicoclinico = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, string>.Entry(
                        "historicoclinico",
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._historicoclinico_Stub,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._historicoclinico_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._historicoclinico_Validate,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._historicoclinico_GetImplementationValue,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._historicoclinico_SetImplementationValue,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._historicoclinico_OnValueChanged);
                private static void _historicoclinico_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d, object sf)
                {
                    c(d, ref d._historicoclinico, sf);
                }
                private static bool _historicoclinico_ComputeIsReadOnly(global::LightSwitchApplication.t_historia_clinica_notificacao e)
                {
                    bool result = false;
                    e.historicoclinico_IsReadOnly(ref result);
                    return result;
                }
                private static void _historicoclinico_Validate(global::LightSwitchApplication.t_historia_clinica_notificacao e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.historicoclinico_Validate(r);
                }
                private static string _historicoclinico_GetImplementationValue(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d)
                {
                    return d.ImplementationEntity.historicoclinico;
                }
                private static void _historicoclinico_SetImplementationValue(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d, string v)
                {
                    d.ImplementationEntity.historicoclinico = v;
                }
                private static void _historicoclinico_OnValueChanged(global::LightSwitchApplication.t_historia_clinica_notificacao e)
                {
                    e.historicoclinico_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::System.Nullable<bool>>.Entry
                    valor = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "valor",
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._valor_Stub,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._valor_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._valor_Validate,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._valor_GetImplementationValue,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._valor_SetImplementationValue,
                        global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass.PropertySetProperties._valor_OnValueChanged);
                private static void _valor_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d, object sf)
                {
                    c(d, ref d._valor, sf);
                }
                private static bool _valor_ComputeIsReadOnly(global::LightSwitchApplication.t_historia_clinica_notificacao e)
                {
                    bool result = false;
                    e.valor_IsReadOnly(ref result);
                    return result;
                }
                private static void _valor_Validate(global::LightSwitchApplication.t_historia_clinica_notificacao e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.valor_Validate(r);
                }
                private static global::System.Nullable<bool> _valor_GetImplementationValue(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d)
                {
                    return d.ImplementationEntity.valor;
                }
                private static void _valor_SetImplementationValue(global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.valor = v;
                }
                private static void _valor_OnValueChanged(global::LightSwitchApplication.t_historia_clinica_notificacao e)
                {
                    e.valor_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, int>.Data _ordem;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, string>.Data _notificacao;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::System.Nullable<int>>.Data _id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, string>.Data _historicoclinico;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_historia_clinica_notificacao, global::LightSwitchApplication.t_historia_clinica_notificacao.DetailsClass, global::System.Nullable<bool>>.Data _valor;
            
        }
    
        #endregion
    }
    
    #endregion
}
