

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class t_user : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the t_user entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_user()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_user(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_user> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.t_user.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_user_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_user_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int coduser
        {
            get
            {
                return global::LightSwitchApplication.t_user.DetailsClass.GetValue(this, global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.coduser);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void coduser_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void coduser_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void coduser_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string nome
        {
            get
            {
                return global::LightSwitchApplication.t_user.DetailsClass.GetValue(this, global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.nome);
            }
            set
            {
                global::LightSwitchApplication.t_user.DetailsClass.SetValue(this, global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.nome, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void nome_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void nome_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void nome_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string login
        {
            get
            {
                return global::LightSwitchApplication.t_user.DetailsClass.GetValue(this, global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.login);
            }
            set
            {
                global::LightSwitchApplication.t_user.DetailsClass.SetValue(this, global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.login, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void login_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void login_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void login_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string senha
        {
            get
            {
                return global::LightSwitchApplication.t_user.DetailsClass.GetValue(this, global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.senha);
            }
            set
            {
                global::LightSwitchApplication.t_user.DetailsClass.SetValue(this, global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.senha, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void senha_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void senha_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void senha_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> datareg
        {
            get
            {
                return global::LightSwitchApplication.t_user.DetailsClass.GetValue(this, global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.datareg);
            }
            set
            {
                global::LightSwitchApplication.t_user.DetailsClass.SetValue(this, global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.datareg, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void datareg_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void datareg_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void datareg_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> data
        {
            get
            {
                return global::LightSwitchApplication.t_user.DetailsClass.GetValue(this, global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.data);
            }
            set
            {
                global::LightSwitchApplication.t_user.DetailsClass.SetValue(this, global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.data, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void data_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void data_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void data_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.t_user,
                global::LightSwitchApplication.t_user.DetailsClass,
                global::LightSwitchApplication.t_user.DetailsClass.IImplementation,
                global::LightSwitchApplication.t_user.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.coduser;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass>.Entry
                __t_userEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass>.Entry(
                    global::LightSwitchApplication.t_user.DetailsClass.__t_user_CreateNew,
                    global::LightSwitchApplication.t_user.DetailsClass.__t_user_Created,
                    global::LightSwitchApplication.t_user.DetailsClass.__t_user_AllowSaveWithErrors);
            private static global::LightSwitchApplication.t_user __t_user_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_user> es)
            {
                return new global::LightSwitchApplication.t_user(es);
            }
            private static void __t_user_Created(global::LightSwitchApplication.t_user e)
            {
                e.t_user_Created();
            }
            private static bool __t_user_AllowSaveWithErrors(global::LightSwitchApplication.t_user e)
            {
                bool result = false;
                e.t_user_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.t_user.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, int> coduser
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.coduser) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string> nome
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.nome) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string> login
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.login) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string> senha
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.senha) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, global::System.Nullable<global::System.DateTime>> datareg
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.datareg) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, global::System.Nullable<global::System.DateTime>> data
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties.data) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int coduser { get; }
                new string nome { get; set; }
                new string login { get; set; }
                new string senha { get; set; }
                new global::System.Nullable<global::System.DateTime> datareg { get; set; }
                new global::System.Nullable<global::System.DateTime> data { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, int>.Entry
                    coduser = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, int>.Entry(
                        "coduser",
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._coduser_Stub,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._coduser_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._coduser_Validate,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._coduser_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._coduser_OnValueChanged);
                private static void _coduser_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_user.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, int>.Data> c, global::LightSwitchApplication.t_user.DetailsClass d, object sf)
                {
                    c(d, ref d._coduser, sf);
                }
                private static bool _coduser_ComputeIsReadOnly(global::LightSwitchApplication.t_user e)
                {
                    bool result = false;
                    e.coduser_IsReadOnly(ref result);
                    return result;
                }
                private static void _coduser_Validate(global::LightSwitchApplication.t_user e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.coduser_Validate(r);
                }
                private static int _coduser_GetImplementationValue(global::LightSwitchApplication.t_user.DetailsClass d)
                {
                    return d.ImplementationEntity.coduser;
                }
                private static void _coduser_OnValueChanged(global::LightSwitchApplication.t_user e)
                {
                    e.coduser_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>.Entry
                    nome = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>.Entry(
                        "nome",
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._nome_Stub,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._nome_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._nome_Validate,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._nome_GetImplementationValue,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._nome_SetImplementationValue,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._nome_OnValueChanged);
                private static void _nome_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_user.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_user.DetailsClass d, object sf)
                {
                    c(d, ref d._nome, sf);
                }
                private static bool _nome_ComputeIsReadOnly(global::LightSwitchApplication.t_user e)
                {
                    bool result = false;
                    e.nome_IsReadOnly(ref result);
                    return result;
                }
                private static void _nome_Validate(global::LightSwitchApplication.t_user e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.nome_Validate(r);
                }
                private static string _nome_GetImplementationValue(global::LightSwitchApplication.t_user.DetailsClass d)
                {
                    return d.ImplementationEntity.nome;
                }
                private static void _nome_SetImplementationValue(global::LightSwitchApplication.t_user.DetailsClass d, string v)
                {
                    d.ImplementationEntity.nome = v;
                }
                private static void _nome_OnValueChanged(global::LightSwitchApplication.t_user e)
                {
                    e.nome_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>.Entry
                    login = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>.Entry(
                        "login",
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._login_Stub,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._login_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._login_Validate,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._login_GetImplementationValue,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._login_SetImplementationValue,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._login_OnValueChanged);
                private static void _login_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_user.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_user.DetailsClass d, object sf)
                {
                    c(d, ref d._login, sf);
                }
                private static bool _login_ComputeIsReadOnly(global::LightSwitchApplication.t_user e)
                {
                    bool result = false;
                    e.login_IsReadOnly(ref result);
                    return result;
                }
                private static void _login_Validate(global::LightSwitchApplication.t_user e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.login_Validate(r);
                }
                private static string _login_GetImplementationValue(global::LightSwitchApplication.t_user.DetailsClass d)
                {
                    return d.ImplementationEntity.login;
                }
                private static void _login_SetImplementationValue(global::LightSwitchApplication.t_user.DetailsClass d, string v)
                {
                    d.ImplementationEntity.login = v;
                }
                private static void _login_OnValueChanged(global::LightSwitchApplication.t_user e)
                {
                    e.login_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>.Entry
                    senha = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>.Entry(
                        "senha",
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._senha_Stub,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._senha_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._senha_Validate,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._senha_GetImplementationValue,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._senha_SetImplementationValue,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._senha_OnValueChanged);
                private static void _senha_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_user.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_user.DetailsClass d, object sf)
                {
                    c(d, ref d._senha, sf);
                }
                private static bool _senha_ComputeIsReadOnly(global::LightSwitchApplication.t_user e)
                {
                    bool result = false;
                    e.senha_IsReadOnly(ref result);
                    return result;
                }
                private static void _senha_Validate(global::LightSwitchApplication.t_user e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.senha_Validate(r);
                }
                private static string _senha_GetImplementationValue(global::LightSwitchApplication.t_user.DetailsClass d)
                {
                    return d.ImplementationEntity.senha;
                }
                private static void _senha_SetImplementationValue(global::LightSwitchApplication.t_user.DetailsClass d, string v)
                {
                    d.ImplementationEntity.senha = v;
                }
                private static void _senha_OnValueChanged(global::LightSwitchApplication.t_user e)
                {
                    e.senha_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    datareg = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "datareg",
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._datareg_Stub,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._datareg_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._datareg_Validate,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._datareg_GetImplementationValue,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._datareg_SetImplementationValue,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._datareg_OnValueChanged);
                private static void _datareg_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_user.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.t_user.DetailsClass d, object sf)
                {
                    c(d, ref d._datareg, sf);
                }
                private static bool _datareg_ComputeIsReadOnly(global::LightSwitchApplication.t_user e)
                {
                    bool result = false;
                    e.datareg_IsReadOnly(ref result);
                    return result;
                }
                private static void _datareg_Validate(global::LightSwitchApplication.t_user e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.datareg_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _datareg_GetImplementationValue(global::LightSwitchApplication.t_user.DetailsClass d)
                {
                    return d.ImplementationEntity.datareg;
                }
                private static void _datareg_SetImplementationValue(global::LightSwitchApplication.t_user.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.datareg = global::LightSwitchApplication.t_user.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _datareg_OnValueChanged(global::LightSwitchApplication.t_user e)
                {
                    e.datareg_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    data = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "data",
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._data_Stub,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._data_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._data_Validate,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._data_GetImplementationValue,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._data_SetImplementationValue,
                        global::LightSwitchApplication.t_user.DetailsClass.PropertySetProperties._data_OnValueChanged);
                private static void _data_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_user.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.t_user.DetailsClass d, object sf)
                {
                    c(d, ref d._data, sf);
                }
                private static bool _data_ComputeIsReadOnly(global::LightSwitchApplication.t_user e)
                {
                    bool result = false;
                    e.data_IsReadOnly(ref result);
                    return result;
                }
                private static void _data_Validate(global::LightSwitchApplication.t_user e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.data_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _data_GetImplementationValue(global::LightSwitchApplication.t_user.DetailsClass d)
                {
                    return d.ImplementationEntity.data;
                }
                private static void _data_SetImplementationValue(global::LightSwitchApplication.t_user.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.data = global::LightSwitchApplication.t_user.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _data_OnValueChanged(global::LightSwitchApplication.t_user e)
                {
                    e.data_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, int>.Data _coduser;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>.Data _nome;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>.Data _login;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, string>.Data _senha;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _datareg;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_user, global::LightSwitchApplication.t_user.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _data;
            
        }
    
        #endregion
    }
    
    #endregion
}
