

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class t_resultadosppe : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the t_resultadosppe entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_resultadosppe()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_resultadosppe(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_resultadosppe> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.t_resultadosppe.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_resultadosppe_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_resultadosppe_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int codresultado
        {
            get
            {
                return global::LightSwitchApplication.t_resultadosppe.DetailsClass.GetValue(this, global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties.codresultado);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codresultado_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codresultado_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codresultado_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string resultado
        {
            get
            {
                return global::LightSwitchApplication.t_resultadosppe.DetailsClass.GetValue(this, global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties.resultado);
            }
            set
            {
                global::LightSwitchApplication.t_resultadosppe.DetailsClass.SetValue(this, global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties.resultado, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void resultado_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void resultado_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void resultado_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.t_resultadosppe,
                global::LightSwitchApplication.t_resultadosppe.DetailsClass,
                global::LightSwitchApplication.t_resultadosppe.DetailsClass.IImplementation,
                global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties.codresultado;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass>.Entry
                __t_resultadosppeEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass>.Entry(
                    global::LightSwitchApplication.t_resultadosppe.DetailsClass.__t_resultadosppe_CreateNew,
                    global::LightSwitchApplication.t_resultadosppe.DetailsClass.__t_resultadosppe_Created,
                    global::LightSwitchApplication.t_resultadosppe.DetailsClass.__t_resultadosppe_AllowSaveWithErrors);
            private static global::LightSwitchApplication.t_resultadosppe __t_resultadosppe_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_resultadosppe> es)
            {
                return new global::LightSwitchApplication.t_resultadosppe(es);
            }
            private static void __t_resultadosppe_Created(global::LightSwitchApplication.t_resultadosppe e)
            {
                e.t_resultadosppe_Created();
            }
            private static bool __t_resultadosppe_AllowSaveWithErrors(global::LightSwitchApplication.t_resultadosppe e)
            {
                bool result = false;
                e.t_resultadosppe_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass, int> codresultado
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties.codresultado) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass, string> resultado
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties.resultado) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int codresultado { get; }
                new string resultado { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass, int>.Entry
                    codresultado = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass, int>.Entry(
                        "codresultado",
                        global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties._codresultado_Stub,
                        global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties._codresultado_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties._codresultado_Validate,
                        global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties._codresultado_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties._codresultado_OnValueChanged);
                private static void _codresultado_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_resultadosppe.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass, int>.Data> c, global::LightSwitchApplication.t_resultadosppe.DetailsClass d, object sf)
                {
                    c(d, ref d._codresultado, sf);
                }
                private static bool _codresultado_ComputeIsReadOnly(global::LightSwitchApplication.t_resultadosppe e)
                {
                    bool result = false;
                    e.codresultado_IsReadOnly(ref result);
                    return result;
                }
                private static void _codresultado_Validate(global::LightSwitchApplication.t_resultadosppe e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.codresultado_Validate(r);
                }
                private static int _codresultado_GetImplementationValue(global::LightSwitchApplication.t_resultadosppe.DetailsClass d)
                {
                    return d.ImplementationEntity.codresultado;
                }
                private static void _codresultado_OnValueChanged(global::LightSwitchApplication.t_resultadosppe e)
                {
                    e.codresultado_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass, string>.Entry
                    resultado = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass, string>.Entry(
                        "resultado",
                        global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties._resultado_Stub,
                        global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties._resultado_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties._resultado_Validate,
                        global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties._resultado_GetImplementationValue,
                        global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties._resultado_SetImplementationValue,
                        global::LightSwitchApplication.t_resultadosppe.DetailsClass.PropertySetProperties._resultado_OnValueChanged);
                private static void _resultado_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_resultadosppe.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_resultadosppe.DetailsClass d, object sf)
                {
                    c(d, ref d._resultado, sf);
                }
                private static bool _resultado_ComputeIsReadOnly(global::LightSwitchApplication.t_resultadosppe e)
                {
                    bool result = false;
                    e.resultado_IsReadOnly(ref result);
                    return result;
                }
                private static void _resultado_Validate(global::LightSwitchApplication.t_resultadosppe e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.resultado_Validate(r);
                }
                private static string _resultado_GetImplementationValue(global::LightSwitchApplication.t_resultadosppe.DetailsClass d)
                {
                    return d.ImplementationEntity.resultado;
                }
                private static void _resultado_SetImplementationValue(global::LightSwitchApplication.t_resultadosppe.DetailsClass d, string v)
                {
                    d.ImplementationEntity.resultado = v;
                }
                private static void _resultado_OnValueChanged(global::LightSwitchApplication.t_resultadosppe e)
                {
                    e.resultado_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass, int>.Data _codresultado;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadosppe, global::LightSwitchApplication.t_resultadosppe.DetailsClass, string>.Data _resultado;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class t_resultadoteste : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the t_resultadoteste entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_resultadoteste()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public t_resultadoteste(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_resultadoteste> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.t_resultadoteste.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_resultadoteste_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void t_resultadoteste_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int codigo
        {
            get
            {
                return global::LightSwitchApplication.t_resultadoteste.DetailsClass.GetValue(this, global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties.codigo);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codigo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codigo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void codigo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string resultadoteste
        {
            get
            {
                return global::LightSwitchApplication.t_resultadoteste.DetailsClass.GetValue(this, global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties.resultadoteste);
            }
            set
            {
                global::LightSwitchApplication.t_resultadoteste.DetailsClass.SetValue(this, global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties.resultadoteste, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void resultadoteste_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void resultadoteste_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void resultadoteste_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.t_resultadoteste,
                global::LightSwitchApplication.t_resultadoteste.DetailsClass,
                global::LightSwitchApplication.t_resultadoteste.DetailsClass.IImplementation,
                global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties.codigo;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass>.Entry
                __t_resultadotesteEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass>.Entry(
                    global::LightSwitchApplication.t_resultadoteste.DetailsClass.__t_resultadoteste_CreateNew,
                    global::LightSwitchApplication.t_resultadoteste.DetailsClass.__t_resultadoteste_Created,
                    global::LightSwitchApplication.t_resultadoteste.DetailsClass.__t_resultadoteste_AllowSaveWithErrors);
            private static global::LightSwitchApplication.t_resultadoteste __t_resultadoteste_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.t_resultadoteste> es)
            {
                return new global::LightSwitchApplication.t_resultadoteste(es);
            }
            private static void __t_resultadoteste_Created(global::LightSwitchApplication.t_resultadoteste e)
            {
                e.t_resultadoteste_Created();
            }
            private static bool __t_resultadoteste_AllowSaveWithErrors(global::LightSwitchApplication.t_resultadoteste e)
            {
                bool result = false;
                e.t_resultadoteste_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass, int> codigo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties.codigo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass, string> resultadoteste
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties.resultadoteste) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int codigo { get; }
                new string resultadoteste { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass, int>.Entry
                    codigo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass, int>.Entry(
                        "codigo",
                        global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties._codigo_Stub,
                        global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties._codigo_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties._codigo_Validate,
                        global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties._codigo_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties._codigo_OnValueChanged);
                private static void _codigo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_resultadoteste.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass, int>.Data> c, global::LightSwitchApplication.t_resultadoteste.DetailsClass d, object sf)
                {
                    c(d, ref d._codigo, sf);
                }
                private static bool _codigo_ComputeIsReadOnly(global::LightSwitchApplication.t_resultadoteste e)
                {
                    bool result = false;
                    e.codigo_IsReadOnly(ref result);
                    return result;
                }
                private static void _codigo_Validate(global::LightSwitchApplication.t_resultadoteste e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.codigo_Validate(r);
                }
                private static int _codigo_GetImplementationValue(global::LightSwitchApplication.t_resultadoteste.DetailsClass d)
                {
                    return d.ImplementationEntity.codigo;
                }
                private static void _codigo_OnValueChanged(global::LightSwitchApplication.t_resultadoteste e)
                {
                    e.codigo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass, string>.Entry
                    resultadoteste = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass, string>.Entry(
                        "resultadoteste",
                        global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties._resultadoteste_Stub,
                        global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties._resultadoteste_ComputeIsReadOnly,
                        global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties._resultadoteste_Validate,
                        global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties._resultadoteste_GetImplementationValue,
                        global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties._resultadoteste_SetImplementationValue,
                        global::LightSwitchApplication.t_resultadoteste.DetailsClass.PropertySetProperties._resultadoteste_OnValueChanged);
                private static void _resultadoteste_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.t_resultadoteste.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass, string>.Data> c, global::LightSwitchApplication.t_resultadoteste.DetailsClass d, object sf)
                {
                    c(d, ref d._resultadoteste, sf);
                }
                private static bool _resultadoteste_ComputeIsReadOnly(global::LightSwitchApplication.t_resultadoteste e)
                {
                    bool result = false;
                    e.resultadoteste_IsReadOnly(ref result);
                    return result;
                }
                private static void _resultadoteste_Validate(global::LightSwitchApplication.t_resultadoteste e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.resultadoteste_Validate(r);
                }
                private static string _resultadoteste_GetImplementationValue(global::LightSwitchApplication.t_resultadoteste.DetailsClass d)
                {
                    return d.ImplementationEntity.resultadoteste;
                }
                private static void _resultadoteste_SetImplementationValue(global::LightSwitchApplication.t_resultadoteste.DetailsClass d, string v)
                {
                    d.ImplementationEntity.resultadoteste = v;
                }
                private static void _resultadoteste_OnValueChanged(global::LightSwitchApplication.t_resultadoteste e)
                {
                    e.resultadoteste_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass, int>.Data _codigo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.t_resultadoteste, global::LightSwitchApplication.t_resultadoteste.DetailsClass, string>.Data _resultadoteste;
            
        }
    
        #endregion
    }
    
    #endregion
}
